version: "3"
services:
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:15.2-alpine
    volumes:
      - ./etc/postgres_data/psql:/var/lib/postgresql/data
      - ./src/database/scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - TZ=Australia/NSW
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}